/**
 * Earlier prompt editions, kept so the bench can put them beside the current one.
 *
 * WHY THESE EXIST. The analysis bench compares prompt versions as well as
 * models, from ONE retrieval: every selected version is built from the same
 * documents and every selected model answers each. That needs the older
 * questions and rules to still be in the code. The library job never reads
 * this file - it always writes with the current edition in ./prompt.ts.
 *
 * AN EDITION IS ONLY ITS QUESTIONS AND RULES. The header, the source block, the
 * TASK lines, the retrieval-mode rule and the output contract are identical
 * across every version listed here - checked when these were extracted, by
 * rendering each version's own prompt.ts from git history and comparing every
 * other line. A future version that changes one of those shared parts cannot be
 * archived as an edition of this shape; it needs that part added to the shape
 * first.
 *
 * GENERATED, NOT HAND-COPIED. The strings were read back out of each version's
 * rendered prompt, so they are byte-for-byte what that version sent. Do not edit
 * them: a "fixed" archived edition is no longer the version its number names,
 * and every stored bench run labelled with it would be mislabelled.
 *
 * Version 10 was a bench-only draft and never current; it is archived because
 * bench runs are labelled with it.
 *
 * To archive the current edition when the next version ships, add it here with
 * its questions and rules exactly as they stand, then change ./prompt.ts.
 */
import type { PromptEdition } from './prompt.js'

export const ARCHIVED_PROMPT_EDITIONS: readonly PromptEdition[] = [
  {
    version: 7,
    movieQuestions: [
      { id: 'work', text: "What is this film doing, and how do its choices serve that? Name a choice, then say what it achieves - a list of equipment or techniques with no effect attached is not an answer." },
      { id: 'tradition', text: "What tradition does it sit in - what was it responding to, what did it influence? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there." },
      { id: 'intent', text: "What did the people who made it say they were trying to do?" },
      { id: 'circumstances', text: "What circumstances of its making or first release left a mark on the work - how it was produced, the form it was originally shown in, constraints or controversies that changed what it became? Facts that did not change the work - budgets, shooting schedules, crew and extras counts, release dates - are not answers." },
      { id: 'dispute', text: "What do critics genuinely disagree about? Report the disagreement and leave it open - if you find yourself concluding which side is right, you have stopped answering this question." },
    ],
    seriesQuestions: [
      { id: 'work', text: "What is this series doing, and how do its choices serve that? Name a choice, then say what it achieves - a list of equipment or techniques with no effect attached is not an answer." },
      { id: 'structure', text: "How is it structured across its run - serialised or episodic, and did it change?" },
      { id: 'tradition', text: "What tradition does it sit in - what was it responding to, what did it influence? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there." },
      { id: 'intent', text: "What did the people who made it say they were trying to do?" },
      { id: 'circumstances', text: "What circumstances of its making or first release left a mark on the work - how it was produced, the form it was originally shown in, constraints or controversies that changed what it became? Facts that did not change the work - budgets, shooting schedules, crew and extras counts, release dates - are not answers." },
      { id: 'dispute', text: "What do critics genuinely disagree about? Report the disagreement and leave it open - if you find yourself concluding which side is right, you have stopped answering this question." },
    ],
    rules: [
      "Describe how it works, never what happens in it. No third-act or ending discussion. Someone who has not seen it must be able to read this safely.",
      "Match your register to the work. A stunt-driven action picture has real craft in its staging and choreography, and that is a legitimate subject - write about it as what it is. Do not apply art-cinema vocabulary to a genre entertainment.",
      "The questions are what to cover and in what order, not a form to fill in. Do not write one paragraph per question. Merge the ones that belong together and let the whole read as continuous prose with a single line of thought.",
      "Write in short paragraphs of three or four sentences, separated by a blank line. Keep each sentence to one idea and do not chain clauses with semicolons - if a sentence carries two ideas, make it two sentences. Plain prose only in the analysis itself: no headings, bullet points, numbered lists or bold text.",
      "Be specific. Name the people the sources name - the director, the writer, the cinematographer, whoever is credited with the choice you are describing - rather than writing \"those behind the project\" or \"the creative team\". Cut any sentence whose only content is that the work sits in a tradition, extends one, or hopes to influence something: say what and how, or say nothing.",
      "Answer only what the sources genuinely support. It is normal for two or three of these questions to have no answer, and dropping them is the correct outcome rather than a gap to fill. If none of them do, say so in two sentences and stop.",
      "Do not cite, number or link the sources in your prose, and do not quote the reception figures back.",
      "Length follows the work and the sources. Some support 900 words. Many support 200.",
    ],
  },
  {
    version: 8,
    movieQuestions: [
      { id: 'work', text: "What is this film doing, and how do its choices serve that? Name a choice, then say what it achieves - a list of equipment or techniques with no effect attached is not an answer." },
      { id: 'tradition', text: "What tradition does it sit in - what was it responding to, what did it influence? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there." },
      { id: 'intent', text: "What did the people who made it say they were trying to do?" },
      { id: 'circumstances', text: "What circumstances of its making or first release left a mark on the work - how it was produced, the form it was originally shown in, constraints or controversies that changed what it became? Facts that did not change the work - budgets, shooting schedules, crew and extras counts, release dates - are not answers. Neither is how it was received: marketing, online discussion and who objected to it after release belong to the disagreement question, not this one. Ask whether the finished work would be different if this had not happened." },
      { id: 'dispute', text: "What do critics genuinely disagree about? Report the disagreement and leave it open - if you find yourself concluding which side is right, you have stopped answering this question." },
    ],
    seriesQuestions: [
      { id: 'work', text: "What is this series doing, and how do its choices serve that? Name a choice, then say what it achieves - a list of equipment or techniques with no effect attached is not an answer." },
      { id: 'structure', text: "How is it structured across its run - serialised or episodic, and did it change?" },
      { id: 'tradition', text: "What tradition does it sit in - what was it responding to, what did it influence? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there." },
      { id: 'intent', text: "What did the people who made it say they were trying to do?" },
      { id: 'circumstances', text: "What circumstances of its making or first release left a mark on the work - how it was produced, the form it was originally shown in, constraints or controversies that changed what it became? Facts that did not change the work - budgets, shooting schedules, crew and extras counts, release dates - are not answers. Neither is how it was received: marketing, online discussion and who objected to it after release belong to the disagreement question, not this one. Ask whether the finished work would be different if this had not happened." },
      { id: 'dispute', text: "What do critics genuinely disagree about? Report the disagreement and leave it open - if you find yourself concluding which side is right, you have stopped answering this question." },
    ],
    rules: [
      "Describe how it works, never what happens in it. No third-act or ending discussion. Someone who has not seen it must be able to read this safely.",
      "Match your register to the work. A stunt-driven action picture has real craft in its staging and choreography, and that is a legitimate subject - write about it as what it is. Do not apply art-cinema vocabulary to a genre entertainment.",
      "The questions are what to cover and in what order, not a form to fill in. Give a question as many paragraphs as the sources support, and none to a question they do not. Two questions may share a paragraph when they genuinely belong together, but do not scatter one question across paragraphs that are not next to each other. Let the whole read as continuous prose with a single line of thought.",
      "Write in short paragraphs of three or four sentences, separated by a blank line. Keep each sentence to one idea and do not chain clauses with semicolons - if a sentence carries two ideas, make it two sentences. Plain prose only in the analysis itself: no headings, bullet points, numbered lists or bold text.",
      "Be specific. Name the people the sources name - the director, the writer, the cinematographer, whoever is credited with the choice you are describing - rather than writing \"those behind the project\" or \"the creative team\". Cut any sentence whose only content is that the work sits in a tradition, extends one, or hopes to influence something: say what and how, or say nothing.",
      "Answer only what the sources genuinely support. It is normal for two or three of these questions to have no answer, and dropping them is the correct outcome rather than a gap to fill. If none of them do, say so in two sentences and stop.",
      "Do not cite, number or link the sources in your prose, and do not quote the reception figures back. Never refer to the source documents as a thing - no \"the sources say\", \"the sources describe\", \"reportedly\", \"according to reports\". Write the claim as a fact about the work, or name the critic or publication that made it.",
      "Length follows the work, not the amount of source text. Many titles support 200 words, and 900 is the most any of them support. A long source block is not a reason to write more - most of it is plot summary, cast lists and the same facts repeated across pages.",
    ],
  },
  {
    version: 9,
    movieQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, what tradition, movement or body of work does it belong to, what was it responding to? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. What it went on to influence belongs to the reception question." },
      { id: 'work', text: "What is this film doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be." },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what someone actually said, attributed to them, never an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, and name the critic or publication - where the sources include established publications, lead with them. If critics largely agree, say what they agree on. If they genuinely split, say where, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    seriesQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, what tradition, movement or body of work does it belong to, what was it responding to? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. What it went on to influence belongs to the reception question." },
      { id: 'work', text: "What is this series doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be." },
      { id: 'structure', text: "How is it structured across its run - serialised or episodic, and did it change?" },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what someone actually said, attributed to them, never an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, and name the critic or publication - where the sources include established publications, lead with them. If critics largely agree, say what they agree on. If they genuinely split, say where, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    rules: [
      "Describe how it works, never what happens in it. No third-act or ending discussion, and no reveals - not what a character, creature or image turns out to be. Someone who has not seen it must be able to read this safely.",
      "Match your register to the work. A stunt-driven action picture has real craft in its staging and choreography, and that is a legitimate subject - write about it as what it is. Do not apply art-cinema vocabulary to a genre entertainment.",
      "The questions are what to cover and in what order, not a form to fill in. Give a question as many paragraphs as the sources support, and none to a question they do not. Two questions may share a paragraph when they genuinely belong together, but do not scatter one question across paragraphs that are not next to each other. Say each fact once, under the question it belongs to - once it has been said, do not say it again under another.",
      "Write in short paragraphs of three or four sentences, never more, separated by a blank line. Keep each sentence to one idea and do not chain clauses with semicolons - if a sentence carries two ideas, make it two sentences. Each answer is shown to the reader under a heading that names its question, so open on the substance - never with a restatement of the question such as \"The film sits in\", \"The circumstances of its making\" or \"Critics disagree about\". Say what a choice does, not what it avoids: a sentence built on \"rather than\" or \"not X but Y\" usually says one thing twice. Plain prose only in the analysis itself: no headings, bullet points, numbered lists or bold text.",
      "Be specific. Name the person responsible for the choice you are describing - the director, the writer, the cinematographer - instead of \"those behind the project\" or \"the creative team\". Name people for what they chose, never to list credits: a sentence that only records who did what is not analysis. Cut any sentence whose only content is that the work sits in a tradition, extends one, or hopes to influence something: say what and how, or say nothing.",
      "Answer only what the sources genuinely support. It is normal for one or two of these questions to have no answer, and dropping them is the correct outcome rather than a gap to fill. A single thin fact is not a paragraph - fold it into the answer it belongs to, or leave it out. If no question has an answer, say so in two sentences and stop.",
      "Do not cite, number or link the documents, and do not mention them at all - the reader never sees them, so \"the sources say\" or \"the sources carry\" points at nothing. Do not quote the reception figures back. State facts plainly. A view - an interpretation or a judgement - belongs to whoever holds it: name the critic or publication when the sources do, and say \"critics\" when they do not. Never turn a view into a fact, and never hide whose view it is behind \"is described as\", \"has been called\", \"according to one reading\" or \"reportedly\". Name a critic where their view is the point, not in every sentence. Judgements of quality belong in the reception answer only.",
      "Length follows the work, not the amount of source text. Many titles support 200 words, and 900 words - about ten short paragraphs - is the most any of them support. A long source block is not a reason to write more - most of it is plot summary, cast lists and the same facts repeated across pages.",
    ],
  },
  {
    version: 10,
    movieQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, and what earlier works, genres or movements does it belong to or answer? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. How it was made and what its makers decided belong to the making question, and what it went on to influence to the reception question." },
      { id: 'work', text: "What is this film doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be. What a performance, an effect or a score does belongs here; whether it is good belongs to the reception question." },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what a maker is reported as saying, attributed to them. A critic's guess at what the maker wanted is not a statement by the maker, even when it is phrased as \"if he hoped to\", and neither is an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, and name the critic or publication - where the sources include established publications, lead with them. If critics largely agree, say what they agree on. If they genuinely split, say where, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    seriesQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, and what earlier works, genres or movements does it belong to or answer? Name traditions and movements freely. Naming one specific prior work as the model for this one is only safe when the comparison does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. How it was made and what its makers decided belong to the making question, and what it went on to influence to the reception question." },
      { id: 'work', text: "What is this series doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be. What a performance, an effect or a score does belongs here; whether it is good belongs to the reception question." },
      { id: 'structure', text: "How is it structured across its run - serialised or episodic, and did it change?" },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what a maker is reported as saying, attributed to them. A critic's guess at what the maker wanted is not a statement by the maker, even when it is phrased as \"if he hoped to\", and neither is an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, and name the critic or publication - where the sources include established publications, lead with them. If critics largely agree, say what they agree on. If they genuinely split, say where, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    rules: [
      "Describe how it works, never what happens in it. No third-act or ending discussion, and no reveals - not what a character, creature or image turns out to be. Someone who has not seen it must be able to read this safely.",
      "Match your register to the work. A stunt-driven action picture has real craft in its staging and choreography, and that is a legitimate subject - write about it as what it is. Do not apply art-cinema vocabulary to a genre entertainment.",
      "The questions are what to cover and in what order, not a form to fill in. Give a question as many paragraphs as the sources support, and none to a question they do not. Two questions may share a paragraph when they genuinely belong together, but do not scatter one question across paragraphs that are not next to each other. Say each fact once, under the question it belongs to - once it has been said, do not say it again under another.",
      "Write in short paragraphs of three or four sentences, never more, separated by a blank line. Keep each sentence to one idea and do not chain clauses with semicolons - if a sentence carries two ideas, make it two sentences. Each answer is shown to the reader under a heading that names its question, so open on the substance - never with a restatement of the question such as \"The film sits in\", \"The circumstances of its making\" or \"Critics disagree about\". Say what a choice does, not what it avoids: a sentence built on \"rather than\" or \"not X but Y\" usually says one thing twice. Plain prose only in the analysis itself: no headings, bullet points, numbered lists or bold text.",
      "Be specific. Name the person responsible for the choice you are describing - the director, the writer, the cinematographer - instead of \"those behind the project\" or \"the creative team\". Name people for what they chose, never to list credits: a sentence that only records who did what is not analysis. Cut any sentence whose only content is that the work sits in a tradition, extends one, or hopes to influence something: say what and how, or say nothing.",
      "Answer only what the sources genuinely support. It is normal for one or two of these questions to have no answer, and dropping them is the correct outcome rather than a gap to fill. A single thin fact is not a paragraph - fold it into the answer it belongs to, or leave it out. If no question has an answer, say so in two sentences and stop.",
      "Do not cite, number or link the documents, and do not mention them at all - the reader never sees them, so \"the sources say\" or \"the sources carry\" points at nothing. Do not quote the reception figures back. State facts plainly. A view - an interpretation or a judgement - belongs to whoever holds it: name the critic or publication when the sources do, and say \"critics\" when they do not. Never turn a view into a fact, and never hide whose view it is behind \"is described as\", \"has been called\", \"according to one reading\" or \"reportedly\". A view written as a plain sentence with nobody named is still a view: \"the score makes the violence feel inevitable\" is somebody's reading and needs their name. When a paragraph draws on one critic's reading throughout, name them once, at its start. Praise or faults of a performance, an effect or a script are judgements, and judgements of quality belong in the reception answer only.",
      "Length follows the work, not the amount of source text. Many titles support 200 words, and 900 words - about ten short paragraphs - is the most any of them support. A long source block is not a reason to write more - most of it is plot summary, cast lists and the same facts repeated across pages.",
    ],
  },
  {
    version: 11,
    movieQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, and what tradition, movement or body of work does it belong to? Open on that, not on who directed, wrote or stars in it - the reader can already see the credits. Name traditions and movements freely. A comparison with one specific earlier work - that this one borrows from it, is modelled on it or answers it - is a view unless a maker said it, so name who made the comparison. It is only safe when it does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. How it was made and what its makers decided belong to the making question, and what it went on to influence to the reception question." },
      { id: 'work', text: "What is this film doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be. Keep to what the work plainly does - how it is shot, scored, staged and performed. What one critic reads into a choice belongs to the reception answer, under their name. What a performance, an effect or a score does belongs here; whether it is good belongs to the reception question." },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what a maker is reported as saying, attributed to them. A critic's guess at what the maker wanted is not a statement by the maker, even when it is phrased as \"if he hoped to\", and neither is an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, grouped by the point made: one sentence per point, naming every critic or publication who made it (\"Roger Ebert and Derek Malcolm praised the effects\"), not one sentence per critic. Keep each point with the critic who made it. Where the sources include established publications, lead with them. A review of a later re-release or restoration is not how the work was first received - say so when a view dates from one. If critics largely agree, say what they agree on. If they genuinely split, describe the split only in terms a critic used, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    seriesQuestions: [
      { id: 'tradition', text: "Where does it come from - what kind of work is it, what source does it adapt, and what tradition, movement or body of work does it belong to? Open on that, not on who directed, wrote or stars in it - the reader can already see the credits. Name traditions and movements freely. A comparison with one specific earlier work - that this one borrows from it, is modelled on it or answers it - is a view unless a maker said it, so name who made the comparison. It is only safe when it does not carry the ending of that work across: if a reader who knows how that one ends would then know how this one ends, name the tradition and stop there. How it was made and what its makers decided belong to the making question, and what it went on to influence to the reception question." },
      { id: 'work', text: "What is this series doing, and how do its choices serve that? Name a choice, then say what it achieves. Only the choices that matter to what it is doing: a run of camera models, lens makes or music credits is not an answer, even with a sentence about its effect attached. Describe what an image, device or figure does to the viewer, never what it turns out to be. Keep to what the work plainly does - how it is shot, scored, staged and performed. What one critic reads into a choice belongs to the reception answer, under their name. What a performance, an effect or a score does belongs here; whether it is good belongs to the reception question." },
      { id: 'structure', text: "How is it structured across its run - serialised or episodic, and did it change?" },
      { id: 'circumstances', text: "How was it made, and what did that leave on the work? Two things belong here. First, what the people who made it said they were trying to do - only what a maker is reported as saying, attributed to them. A critic's guess at what the maker wanted is not a statement by the maker, even when it is phrased as \"if he hoped to\", and neither is an intention read back off the finished work. Second, the circumstances of its making or first release that changed what it became - how it was produced, the form it was first shown in, the constraints it was made under. Ask whether the finished work would be different if this had not happened. Facts that did not change the work are not answers - budgets, shooting schedules, crew and extras counts, filming locations listed for their own sake, release dates, coincidences. Neither is how it was received: that belongs to the reception question." },
      { id: 'reception', text: "How was it received, and what did it go on to influence? Say what critics valued in it and what they faulted, grouped by the point made: one sentence per point, naming every critic or publication who made it (\"Roger Ebert and Derek Malcolm praised the effects\"), not one sentence per critic. Keep each point with the critic who made it. Where the sources include established publications, lead with them. A review of a later re-release or restoration is not how the work was first received - say so when a view dates from one. If critics largely agree, say what they agree on. If they genuinely split, describe the split only in terms a critic used, give each side once and move on, with no sentence remarking that the question stays open. Critics reading the same work in different ways is not a disagreement about it. A criticism of one part may name that part - the final act, a subplot - but not say what happens in it. No scores, no list of awards, and no verdict of your own." },
    ],
    rules: [
      "Describe how it works, never what happens in it. No third-act or ending discussion, and no reveals - not what a character, creature or image turns out to be. Someone who has not seen it must be able to read this safely.",
      "Match your register to the work. A stunt-driven action picture has real craft in its staging and choreography, and that is a legitimate subject - write about it as what it is. Do not apply art-cinema vocabulary to a genre entertainment.",
      "The questions are what to cover and in what order, not a form to fill in. Give a question as many paragraphs as the sources support, and none to a question they do not. Two questions may share a paragraph when they genuinely belong together, but do not scatter one question across paragraphs that are not next to each other. Say each fact once, under the question it belongs to - once it has been said, do not say it again under another.",
      "Write in short paragraphs of three or four sentences, never more, separated by a blank line. Keep each sentence to one idea and do not chain clauses with semicolons - if a sentence carries two ideas, make it two sentences. Connect the sentences of a paragraph into one line of thought: a run of short statements that do not lead into each other reads as notes. Each answer is shown to the reader under a heading that names its question, so open on the substance - never with a restatement of the question such as \"The film sits in\", \"The circumstances of its making\" or \"Critics disagree about\". Say what a choice does, not what it avoids: a sentence built on \"rather than\" or \"not X but Y\" usually says one thing twice. Plain prose only in the analysis itself: no headings, bullet points, numbered lists or bold text.",
      "Be specific. Name the person responsible for the choice you are describing - the director, the writer, the cinematographer - instead of \"those behind the project\" or \"the creative team\". Name people for what they chose, never to list credits: a sentence that only records who did what is not analysis. Cut any sentence whose only content is that the work sits in a tradition, extends one, or hopes to influence something: say what and how, or say nothing.",
      "Answer only what the sources genuinely support. It is normal for one or two of these questions to have no answer, and dropping them is the correct outcome rather than a gap to fill. A single thin fact is not a paragraph - fold it into the answer it belongs to, or leave it out. If no question has an answer, say so in two sentences and stop.",
      "Do not cite, number or link the documents, and do not mention them at all - the reader never sees them, so \"the sources say\" or \"the sources carry\" points at nothing. Do not quote the reception figures back. State facts plainly. A view - an interpretation, a judgement or a comparison with another work - belongs to whoever holds it: name the critic or publication when the sources do, and say \"critics\" when they do not. Never turn a view into a fact, and never hide whose view it is behind \"is described as\", \"has been called\", \"according to one reading\" or \"reportedly\". A view written as a plain sentence with nobody named is still a view: \"the score makes the violence feel inevitable\" is somebody's reading and needs their name, and so does \"it borrows from\" another film. When a paragraph draws on one critic's reading throughout, name them once, at its start. Praise or faults of a performance, an effect or a script are judgements, and judgements of quality belong in the reception answer only.",
      "Length follows the work, not the amount of source text. Many titles support 200 words, and 900 words - about ten short paragraphs - is the most any of them support. A long source block is not a reason to write more - most of it is plot summary, cast lists and the same facts repeated across pages.",
    ],
  },
]
